<script setup lang="ts">
import TaskTimeline from './TaskTimeline.vue'
import { statusMeta } from '../../utils/status'
import { formatDateTime } from '../../utils/time'
import type { AsyncTask } from '../../types/api'
defineProps<{ modelValue: boolean; task: AsyncTask | null; loading: boolean; canRecover: boolean; submitting?: boolean }>()
const emit = defineEmits<{ 'update:modelValue': [value: boolean]; retry: [taskId: number]; reconcile: [taskId: number] }>()
const text = (value?: string | number | null) => value === undefined || value === null || value === '' ? '-' : String(value)
const time = formatDateTime
</script>
<template>
  <el-drawer :model-value="modelValue" size="min(620px, 100%)" direction="rtl" @update:model-value="emit('update:modelValue', $event)"><template #header><div><strong>异步任务详情</strong><div class="muted">{{ task?.taskNo || '任务详情' }}</div></div></template><el-skeleton :loading="loading" animated :rows="10"><template #default><template v-if="task"><el-descriptions :column="1" border size="small"><el-descriptions-item label="任务号">{{ text(task.taskNo) }}</el-descriptions-item><el-descriptions-item label="实例"><span>{{ text(task.instanceNo) }}</span><span v-if="task.instanceName" class="muted"> · {{ task.instanceName }}</span></el-descriptions-item><el-descriptions-item label="命令号">{{ text(task.commandId) }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusMeta(task.state).type">{{ statusMeta(task.state).label }}</el-tag></el-descriptions-item><el-descriptions-item label="操作">{{ text(task.operation) }}</el-descriptions-item><el-descriptions-item label="自动重试">{{ task.retryCount || 0 }}</el-descriptions-item><el-descriptions-item label="下次自动重试">{{ time(task.nextRetryAt) }}</el-descriptions-item><el-descriptions-item label="人工重试">{{ task.manualRetryCount || 0 }}</el-descriptions-item><el-descriptions-item label="回调截止时间">{{ time(task.deadlineAt) }}</el-descriptions-item><el-descriptions-item label="最后错误">{{ text(task.lastError) }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ time(task.createdAt) }}</el-descriptions-item><el-descriptions-item label="更新时间">{{ time(task.updatedAt) }}</el-descriptions-item></el-descriptions><h4>处理链路</h4><TaskTimeline :task="task" /><h4>消息与 Outbox</h4><el-descriptions :column="1" border size="small"><el-descriptions-item label="消息号">{{ text(task.messageId) }}</el-descriptions-item><el-descriptions-item label="回调事件号">{{ text(task.engineEventId) }}</el-descriptions-item><el-descriptions-item label="Outbox 事件">{{ text(task.outboxEventId) }}</el-descriptions-item><el-descriptions-item label="Outbox 状态">{{ text(task.outboxState) }}</el-descriptions-item><el-descriptions-item label="Outbox 重试">{{ task.outboxRetryCount || 0 }}</el-descriptions-item><el-descriptions-item label="Outbox 下次重试">{{ time(task.outboxNextRetryAt) }}</el-descriptions-item><el-descriptions-item label="Outbox 错误">{{ text(task.outboxLastError) }}</el-descriptions-item><el-descriptions-item label="来源任务">{{ text(task.sourceTaskId) }}</el-descriptions-item></el-descriptions><div v-if="task.state === 'UNKNOWN' && canRecover" class="actions"><el-button data-test="retry" type="warning" :loading="submitting" @click="emit('retry', task.id)">重新投递</el-button><el-button data-test="reconcile" type="primary" plain :loading="submitting" @click="emit('reconcile', task.id)">人工对账</el-button></div></template><el-empty v-else description="请选择任务查看详情" :image-size="56" /></template></el-skeleton></el-drawer>
</template>
<style scoped>h4{margin:22px 0 10px;font-size:14px}.actions{display:flex;gap:9px;margin-top:16px}</style>
