<script setup lang="ts">
import type { InstanceSummary } from '../../types/api'
import { statusMeta } from '../../utils/status'
type Detail = InstanceSummary & Record<string, any>
defineProps<{ modelValue: boolean; detail?: Detail | null; loading?: boolean }>()
const emit = defineEmits<{ 'update:modelValue': [value: boolean]; retry: [taskId: number] }>()
const time = (value: unknown) => value ? String(value).replace('T', ' ').slice(0, 19) : '-'
const amount = (value: unknown) => value == null ? '-' : `¥${(Number(value) / 100).toLocaleString('zh-CN', { minimumFractionDigits: 2 })}`
const timeline = (detail?: Detail | null): Array<{ label: string; time: unknown; text: string; type: any }> => [{ label: '创建申请', time: detail?.createdAt, text: '冻结余额并提交创建任务', type: 'primary' }, { label: '命令投递', time: detail?.taskCreatedAt || detail?.updatedAt, text: detail?.commandId ? `命令 ${detail.commandId}` : '等待异步命令', type: detail?.commandId ? 'primary' : 'info' }, { label: '当前状态', time: detail?.deletedAt || detail?.updatedAt, text: detail?.status ? statusMeta(detail.status).label : '等待状态', type: detail?.status === 'RUNNING' ? 'success' : detail?.status === 'FAILED' ? 'danger' : 'warning' }]
</script>
<template>
  <el-drawer :model-value="modelValue" size="min(520px, 100%)" direction="rtl" @update:model-value="emit('update:modelValue', $event)"><template #header><div><strong>实例详情</strong><div class="muted">{{ detail?.instanceNo || detail?.name || '实例信息' }}</div></div></template><el-skeleton :loading="loading" animated :rows="8"><template #default><template v-if="detail"><h4>配置与费用</h4><el-descriptions :column="1" border size="small"><el-descriptions-item label="实例名称">{{ detail.name || '-' }}</el-descriptions-item><el-descriptions-item label="实例号">{{ detail.instanceNo || '-' }}</el-descriptions-item><el-descriptions-item label="算力产品">{{ detail.productName || '-' }}</el-descriptions-item><el-descriptions-item label="目标集群">{{ detail.clusterName || '-' }}</el-descriptions-item><el-descriptions-item label="引擎实例 ID">{{ detail.engineInstanceId || '-' }}</el-descriptions-item><el-descriptions-item label="创建费用">{{ amount(detail.creationChargeCent ?? detail.amountCent) }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusMeta(detail.status).type">{{ statusMeta(detail.status).label }}</el-tag></el-descriptions-item></el-descriptions><h4>生命周期</h4><el-timeline><el-timeline-item v-for="item in timeline(detail)" :key="item.label" :timestamp="time(item.time)" :type="item.type">{{ item.label }} · {{ item.text }}</el-timeline-item></el-timeline><h4>相关任务与命令</h4><el-descriptions :column="1" border size="small"><el-descriptions-item label="任务 ID">{{ detail.taskId || detail.task?.id || '-' }}</el-descriptions-item><el-descriptions-item label="命令 ID">{{ detail.commandId || detail.task?.commandId || '-' }}</el-descriptions-item><el-descriptions-item label="重试次数">{{ detail.retryCount ?? detail.task?.retryCount ?? 0 }}</el-descriptions-item><el-descriptions-item label="最近错误">{{ detail.lastError || detail.task?.lastError || '-' }}</el-descriptions-item></el-descriptions><el-button v-if="detail.taskId && detail.status === 'UNKNOWN'" type="warning" plain style="margin-top:12px" @click="emit('retry', detail.taskId)">发起人工对账</el-button><h4>审计记录</h4><div v-if="detail.auditLogs?.length" class="audit-list"><div v-for="log in detail.auditLogs" :key="log.id" class="audit-row"><strong>{{ log.action }}</strong><span>{{ log.result }} · {{ time(log.createdAt) }}</span><small v-if="log.error">{{ log.error }}</small></div></div><el-empty v-else description="暂无可展示的审计记录" :image-size="54" /></template><el-empty v-else description="请选择实例查看详情" /></template></el-skeleton></el-drawer>
</template>
<style scoped>h4{margin:22px 0 10px;font-size:14px}.audit-list{border:1px solid var(--border);border-radius:8px}.audit-row{padding:10px 12px;border-bottom:1px solid var(--border);display:grid;gap:3px;font-size:12px}.audit-row:last-child{border-bottom:0}.audit-row span,.audit-row small{color:var(--muted)}</style>
