package com.yeqimin.computehub.persistence;

import java.time.LocalDateTime;
import java.util.*;
import org.apache.ibatis.annotations.*;

public interface InstanceMapper {
  @Insert("INSERT INTO compute_order(order_no,tenant_id,product_id,product_snapshot,quantity,amount_cent,status,created_by) VALUES(#{orderNo},#{tenantId},#{productId},CAST(#{productSnapshot} AS JSON),#{quantity},#{amountCent},'FROZEN',#{createdBy})") @Options(useGeneratedKeys=true,keyProperty="id") int insertOrder(Map<String,Object> row);
  @Insert("INSERT INTO compute_instance(instance_no,order_id,tenant_id,product_id,cluster_id,name,scenario,status) VALUES(#{instanceNo},#{orderId},#{tenantId},#{productId},#{clusterId},#{name},#{scenario},'REQUESTED')") @Options(useGeneratedKeys=true,keyProperty="id") int insertInstance(Map<String,Object> row);
  @Insert("INSERT INTO async_task(task_no,command_id,tenant_id,instance_id,state,retry_count,next_retry_at) VALUES(#{taskNo},#{commandId},#{tenantId},#{instanceId},'READY',0,NOW(3))") @Options(useGeneratedKeys=true,keyProperty="id") int insertTask(Map<String,Object> row);
  @Insert("INSERT INTO outbox_event(event_id,aggregate_type,aggregate_id,event_type,payload,state,retry_count,next_retry_at) VALUES(#{eventId},'INSTANCE',#{instanceId},'CREATE_INSTANCE',CAST(#{payload} AS JSON),'READY',0,NOW(3))") int insertOutbox(Map<String,Object> row);
  @Select("SELECT i.id,i.instance_no instanceNo,i.tenant_id tenantId,i.name,i.scenario,i.engine_instance_id engineInstanceId,i.status,p.name productName,p.sku,p.gpu_model gpuModel,p.gpu_count gpuCount,c.name clusterName,c.code clusterCode,o.order_no orderNo,o.amount_cent amountCent,i.created_at createdAt,i.updated_at updatedAt,t.id taskId,t.task_no taskNo,t.command_id commandId,t.state taskState,t.retry_count retryCount,t.last_error lastError FROM compute_instance i JOIN compute_order o ON o.id=i.order_id JOIN compute_product p ON p.id=i.product_id JOIN compute_cluster c ON c.id=i.cluster_id LEFT JOIN async_task t ON t.instance_id=i.id WHERE i.id=#{id}")
  Map<String,Object> instance(long id);
  @Select("SELECT i.id,i.instance_no instanceNo,i.tenant_id tenantId,i.name,i.scenario,i.engine_instance_id engineInstanceId,i.status,p.name productName,p.gpu_model gpuModel,p.gpu_count gpuCount,c.name clusterName,o.order_no orderNo,o.amount_cent amountCent,i.created_at createdAt,t.id taskId,t.command_id commandId,t.state taskState,t.retry_count retryCount,t.last_error lastError FROM compute_instance i JOIN compute_order o ON o.id=i.order_id JOIN compute_product p ON p.id=i.product_id JOIN compute_cluster c ON c.id=i.cluster_id LEFT JOIN async_task t ON t.instance_id=i.id WHERE (#{tenantId} IS NULL OR i.tenant_id=#{tenantId}) AND (#{status} IS NULL OR #{status}='' OR i.status=#{status}) ORDER BY i.created_at DESC,i.id DESC LIMIT #{size} OFFSET #{offset}")
  List<Map<String,Object>> instances(@Param("tenantId")Long tenantId,@Param("status")String status,@Param("offset")int offset,@Param("size")int size);
  @Select("SELECT COUNT(*) FROM compute_instance WHERE (#{tenantId} IS NULL OR tenant_id=#{tenantId}) AND (#{status} IS NULL OR #{status}='' OR status=#{status})") long instanceCount(@Param("tenantId")Long tenantId,@Param("status")String status);
  @Select("SELECT t.id taskId,t.task_no taskNo,t.command_id commandId,t.tenant_id tenantId,t.instance_id instanceId,t.state taskState,t.retry_count retryCount,t.deadline_at deadlineAt,t.last_error,i.status instanceStatus,i.scenario,i.instance_no instanceNo,i.order_id orderId,o.order_no orderNo,o.amount_cent amountCent FROM async_task t JOIN compute_instance i ON i.id=t.instance_id JOIN compute_order o ON o.id=i.order_id WHERE t.command_id=#{commandId}") Map<String,Object> taskByCommand(String commandId);
  @Select("SELECT t.id taskId,t.task_no taskNo,t.command_id commandId,t.tenant_id tenantId,t.instance_id instanceId,t.state taskState,t.retry_count retryCount,t.deadline_at deadlineAt,t.last_error,i.status instanceStatus,i.scenario,i.instance_no instanceNo,i.order_id orderId,o.order_no orderNo,o.amount_cent amountCent FROM async_task t JOIN compute_instance i ON i.id=t.instance_id JOIN compute_order o ON o.id=i.order_id WHERE t.id=#{taskId}") Map<String,Object> task(long taskId);
  @Update("UPDATE compute_instance SET status=#{status},engine_instance_id=COALESCE(#{engineId},engine_instance_id) WHERE id=#{id}") int updateInstance(@Param("id")long id,@Param("status")String status,@Param("engineId")String engineId);
  @Update("UPDATE compute_order SET status=#{status} WHERE id=(SELECT order_id FROM compute_instance WHERE id=#{instanceId})") int updateOrderByInstance(@Param("instanceId")long instanceId,@Param("status")String status);
  @Update("UPDATE async_task SET state=#{state},last_error=#{error},version=version+1 WHERE id=#{id}") int updateTask(@Param("id")long id,@Param("state")String state,@Param("error")String error);
  @Insert("INSERT IGNORE INTO inbox_event(engine_event_id,command_id,event_type,payload_hash) VALUES(#{eventId},#{commandId},#{eventType},#{payloadHash})") int insertInbox(Map<String,Object> row);
  @Select("SELECT COUNT(*) FROM compute_instance WHERE (#{tenantId} IS NULL OR tenant_id=#{tenantId}) AND status='RUNNING'") long runningCount(Long tenantId);
}
