<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api'
import { useAuthStore } from '../stores/auth'
type User = {id:number;tenantId:number|null;tenantName:string;username:string;displayName:string;enabled:boolean;roles:string}
type Role = {id:number;code:string;name:string;permissions?:string}
type Page<T> = {items:T[];total:number;page:number;size:number}
const auth=useAuthStore(),route=useRoute(),router=useRouter(),users=ref<User[]>([]), tenants=ref<any[]>([]), roles=ref<Role[]>([]), loading=ref(false), error=ref(''), total=ref(0)
const positiveNumber=(value:unknown,fallback:number)=>{const parsed=Number(value);return Number.isInteger(parsed)&&parsed>0?parsed:fallback}
const readRoute=()=>({keyword:typeof route.query.keyword==='string'?route.query.keyword:'',page:positiveNumber(route.query.page,1),size:positiveNumber(route.query.size,20)})
const query=reactive(readRoute()), roleDialog=ref(false), selected=ref<User|null>(null), selectedRoles=ref<string[]>([])
const canManage=computed(()=>auth.user?.roles.some(role=>role==='PLATFORM_ADMIN'||role==='TENANT_ADMIN')||false)
let ownRouteUpdate=false
const load=async()=>{loading.value=true;error.value='';try{const requests=[api.get<Page<User>>('/users',{params:{keyword:query.keyword||undefined,page:query.page,size:query.size}}),api.get<Role[]>('/roles')];if(auth.isAdmin)requests.push(api.get<Page<any>>('/tenants',{params:{page:1,size:100}}));const values=await Promise.all(requests);users.value=(values[0] as Page<User>).items;total.value=(values[0] as Page<User>).total;roles.value=values[1] as Role[];tenants.value=auth.isAdmin?(values[2] as Page<any>).items:[]}catch(e:any){error.value=`${e.message||'加载失败'}${e.traceId?`（追踪 ID：${e.traceId}）`:''}`}finally{loading.value=false}}
const writeUrl=async()=>{ownRouteUpdate=true;try{await router.replace({query:{...(query.keyword?{keyword:query.keyword}:{}),page:String(query.page),size:String(query.size)}})}finally{ownRouteUpdate=false}}
const search=async()=>{query.page=1;await writeUrl();await load()}
const reset=async()=>{query.keyword='';await search()}
const changePage=async()=>{await writeUrl();await load()}
const openRoles=(user:any)=>{selected.value=user;selectedRoles.value=(user.roles||'').split(',').filter(Boolean);roleDialog.value=true}
const saveRoles=async()=>{if(!selectedRoles.value.length){ElMessage.error('请至少选择一个角色');return}await ElMessageBox.confirm(`确认更新 ${selected.value?.username} 的角色吗？`, '确认角色分配',{type:'warning'});await api.put(`/users/${selected.value!.id}/roles`,{roleCodes:selectedRoles.value});roleDialog.value=false;ElMessage.success('角色已更新');await load()}
const toggle=async(user:any)=>{const enabled=!user.enabled;await ElMessageBox.confirm(`确认${enabled?'启用':'停用'}用户 ${user.username} 吗？`, '确认用户状态',{type:'warning'});await api.put(`/users/${user.id}/enabled`,undefined,{params:{value:enabled}});ElMessage.success(enabled?'用户已启用':'用户已停用');await load()}
watch(()=>route.query,async()=>{if(ownRouteUpdate)return;Object.assign(query,readRoute());await load()})
onMounted(load)
</script>
<template><el-tabs type="border-card" class="panel" style="padding:0"><el-tab-pane v-if="auth.isAdmin" label="租户"><el-table v-loading="loading" :data="tenants" empty-text="暂无租户"><el-table-column prop="code" label="租户编码"/><el-table-column prop="name" label="租户名称"/><el-table-column prop="status" label="状态"><template #default="s"><el-tag :type="s.row.status==='ACTIVE'?'success':'info'">{{s.row.status==='ACTIVE'?'正常':s.row.status}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间"/></el-table></el-tab-pane><el-tab-pane label="用户"><div class="toolbar"><div><el-input v-model="query.keyword" clearable placeholder="搜索账号或姓名" @change="search" @keyup.enter="search"/><el-button @click="search">搜索</el-button><el-button text @click="reset">重置</el-button></div></div><el-alert v-if="error" :title="error" type="error" :closable="false"><template #default><el-button link @click="load">重试</el-button></template></el-alert><el-table v-loading="loading" :data="users" empty-text="暂无匹配用户"><el-table-column prop="username" label="账号"/><el-table-column prop="displayName" label="姓名"/><el-table-column v-if="auth.isAdmin" prop="tenantName" label="所属租户"/><el-table-column prop="roles" label="角色"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column v-if="canManage" label="操作" width="160"><template #default="s"><el-button data-test="mutation" link @click="openRoles(s.row)">分配角色</el-button><el-button data-test="mutation" link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'启用'}}</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" background layout="total, sizes, prev, pager, next" :page-sizes="[20,50,100]" :total="total" @change="changePage"/></div></el-tab-pane><el-tab-pane label="角色与权限"><el-row :gutter="16"><el-col v-for="r in roles" :key="r.id" :span="8"><div class="role-card"><b>{{r.name}}</b><div class="muted">{{r.code}}</div><div class="permissions">{{r.permissions||'无业务权限'}}</div></div></el-col></el-row></el-tab-pane></el-tabs><el-dialog v-model="roleDialog" :title="`分配角色：${selected?.username||''}`" width="430"><el-alert v-if="!auth.isAdmin" title="租户管理员仅能管理本租户，且不可授予平台管理员角色。" type="info" :closable="false" style="margin-bottom:12px"/><el-checkbox-group v-model="selectedRoles"><el-checkbox v-for="role in roles.filter(r=>auth.isAdmin||r.code!=='PLATFORM_ADMIN')" :key="role.code" :label="role.code">{{role.name}}</el-checkbox></el-checkbox-group><template #footer><el-button @click="roleDialog=false">取消</el-button><el-button type="primary" @click="saveRoles">确认分配</el-button></template></el-dialog></template>
<style scoped>.toolbar{margin-bottom:14px}.toolbar .el-input{width:230px;margin-right:8px}.pager{display:flex;justify-content:flex-end;margin-top:16px}.role-card{padding:16px;border:1px solid var(--border);border-radius:10px;margin-bottom:12px}.permissions{margin-top:10px;font-size:12px;color:var(--muted);word-break:break-all}</style>
