<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { init, use, graphic, type ECharts } from 'echarts/core'
import { LineChart, PieChart } from 'echarts/charts'
import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { api } from '../api'

use([LineChart, PieChart, GridComponent, TooltipComponent, LegendComponent, CanvasRenderer])
const summary=ref<any>({}),metrics=ref<any[]>([]),trendEl=ref(),capacityEl=ref(),timer=ref<number>();let trend:ECharts|undefined,capacity:ECharts|undefined;const history:number[]=[];
const money=(v:number)=>`¥${((v||0)/100).toLocaleString('zh-CN',{minimumFractionDigits:2})}`;
const render=()=>{if(!trendEl.value)return;trend??=init(trendEl.value);capacity??=init(capacityEl.value);const gpu=metrics.value[0]?.gpuUtilization||0;history.push(gpu);if(history.length>12)history.shift();trend.setOption({grid:{left:35,right:15,top:25,bottom:25},tooltip:{trigger:'axis'},xAxis:{type:'category',data:history.map((_,i)=>`${i+1}`),axisLine:{lineStyle:{color:'#dfe7ef'}}},yAxis:{type:'value',max:100,splitLine:{lineStyle:{color:'#edf2f6'}}},series:[{type:'line',smooth:true,data:history,showSymbol:false,lineStyle:{width:3,color:'#20a4ae'},areaStyle:{color:new graphic.LinearGradient(0,0,0,1,[{offset:0,color:'#20a4ae55'},{offset:1,color:'#20a4ae03'}])}}]});capacity.setOption({tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['52%','72%'],center:['50%','43%'],label:{show:false},data:[{name:'已分配',value:summary.value.gpuAllocated||0,itemStyle:{color:'#5575ff'}},{name:'空闲',value:(summary.value.gpuTotal||0)-(summary.value.gpuAllocated||0),itemStyle:{color:'#dce6f1'}}]}]})}
const load=async()=>{summary.value=await api.get('/dashboard/summary');metrics.value=await api.get('/metrics/clusters');await nextTick();render()};onMounted(()=>{load();timer.value=window.setInterval(load,5000)});onBeforeUnmount(()=>{clearInterval(timer.value);trend?.dispose();capacity?.dispose()})
</script>
<template><div class="grid stats"><div class="panel stat"><div class="label">GPU 总容量</div><div class="value accent">{{summary.gpuTotal||0}} 卡</div><div class="hint">已分配 {{summary.gpuAllocated||0}} 卡</div></div><div class="panel stat"><div class="label">运行实例</div><div class="value">{{summary.runningInstances||0}}</div><div class="hint">跨 {{summary.clusterCount||0}} 个计算集群</div></div><div class="panel stat"><div class="label">可用余额</div><div class="value money">{{money(summary.availableCent)}}</div><div class="hint">预付费账户</div></div><div class="panel stat"><div class="label">冻结金额</div><div class="value money">{{money(summary.frozenCent)}}</div><div class="hint">等待异步任务结算</div></div></div><div class="grid charts"><div class="panel"><div class="panel-title"><h3>GPU 利用率趋势</h3><span class="muted">每 5 秒刷新 · Mock Engine</span></div><div ref="trendEl" class="chart"/></div><div class="panel"><div class="panel-title"><h3>GPU 容量分配</h3></div><div ref="capacityEl" class="chart"/></div></div><div class="panel" style="margin-top:18px"><div class="panel-title"><h3>集群实时状态</h3><span class="live"><i/>gRPC 指标流正常</span></div><el-table :data="metrics"><el-table-column prop="clusterCode" label="集群"/><el-table-column label="GPU 利用率"><template #default="s"><el-progress :percentage="s.row.gpuUtilization" :stroke-width="8"/></template></el-table-column><el-table-column label="CPU"><template #default="s">{{s.row.cpuUtilization}}%</template></el-table-column><el-table-column label="内存"><template #default="s">{{s.row.memoryUtilization}}%</template></el-table-column></el-table></div></template>
