<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
import { useAuthStore } from '../stores/auth'

type Product = { id:number; sku:string; name:string; gpuModel:string; gpuCount:number; cpuCores:number; memoryGb:number; priceCent:number; enabled:boolean }
type Page = { items: Product[]; total:number; page:number; size:number }
const auth = useAuthStore(), rows = ref<Product[]>([]), total = ref(0), loading = ref(false), error = ref('')
const dialog = ref(false), submitting = ref(false), editing = ref<Product | null>(null)
const query = reactive({ keyword: '', enabled: undefined as boolean | undefined, page: 1, size: 20 })
const form = reactive<Omit<Product, 'id'>>({ sku: '', name: '', gpuModel: '', gpuCount: 1, cpuCores: 1, memoryGb: 1, priceCent: 1, enabled: true })
const canMutate = computed(() => auth.can('product:manage'))
const load = async () => { loading.value = true; error.value = ''; try { const page = await api.get<Page>('/products', { params: { keyword: query.keyword || undefined, enabled: query.enabled, page: query.page, size: query.size } }); rows.value = page.items; total.value = page.total; query.page = page.page; query.size = page.size } catch (e:any) { error.value = `${e.message || '加载失败'}${e.traceId ? `（追踪 ID：${e.traceId}）` : ''}` } finally { loading.value = false } }
const search = async () => { query.page = 1; await load() }
const reset = async () => { Object.assign(query, { keyword: '', enabled: undefined, page: 1 }); await load() }
const open = (row?:any) => { editing.value = row || null; Object.assign(form, row ? { ...row } : { sku: '', name: '', gpuModel: '', gpuCount: 1, cpuCores: 1, memoryGb: 1, priceCent: 1, enabled: true }); dialog.value = true }
const valid = () => form.sku.trim() && form.name.trim() && form.gpuModel.trim() && [form.gpuCount, form.cpuCores, form.memoryGb, form.priceCent].every(value => Number.isInteger(value) && value > 0)
const save = async () => { if (!valid()) { ElMessage.error('请填写 SKU、名称和有效的资源规格、价格'); return } submitting.value = true; try { const data = { name: form.name, gpuModel: form.gpuModel, gpuCount: form.gpuCount, cpuCores: form.cpuCores, memoryGb: form.memoryGb, priceCent: form.priceCent, enabled: form.enabled }; if (editing.value) await api.put(`/products/${editing.value.id}`, data); else await api.post('/products', { ...data, sku: form.sku }); dialog.value = false; ElMessage.success('产品已保存'); await load() } finally { submitting.value = false } }
const toggle = async (row:any) => { const next = !row.enabled; await ElMessageBox.confirm(`确认${next ? '启用' : '停用'}「${row.name}」吗？停用后不会删除历史订单。`, '确认产品状态', { type: 'warning' }); await api.put(`/products/${row.id}`, { name: row.name, gpuModel: row.gpuModel, gpuCount: row.gpuCount, cpuCores: row.cpuCores, memoryGb: row.memoryGb, priceCent: row.priceCent, enabled: next }); ElMessage.success(next ? '产品已启用' : '产品已停用'); await load() }
onMounted(load)
</script>
<template>
  <div class="panel">
    <div class="toolbar"><div class="filters"><el-input v-model="query.keyword" placeholder="搜索 SKU / 产品名称 / GPU" clearable @change="search" @keyup.enter="search"/><el-select v-model="query.enabled" clearable placeholder="全部状态" @change="search"><el-option label="在售" :value="true"/><el-option label="停用" :value="false"/></el-select><el-button @click="search">搜索</el-button><el-button text @click="reset">重置</el-button></div><el-button v-if="canMutate" data-test="mutation" type="primary" @click="open()">新增产品</el-button></div>
    <el-alert v-if="error" :title="error" type="error" :closable="false"><template #default><el-button link type="primary" @click="load">重试</el-button></template></el-alert>
    <el-table v-loading="loading" :data="rows" empty-text="暂无符合条件的产品"><el-table-column prop="sku" label="SKU" width="150"/><el-table-column prop="name" label="产品名称"/><el-table-column prop="gpuModel" label="GPU"><template #default="s">{{s.row.gpuModel}} × {{s.row.gpuCount}}</template></el-table-column><el-table-column label="规格"><template #default="s">{{s.row.cpuCores}} C / {{s.row.memoryGb}} GB</template></el-table-column><el-table-column label="价格"><template #default="s"><b class="money">¥{{(s.row.priceCent/100).toFixed(2)}}</b> / 次</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'在售':'停用'}}</el-tag></template></el-table-column><el-table-column v-if="canMutate" label="操作" width="150"><template #default="s"><el-button data-test="mutation" link type="primary" @click="open(s.row)">编辑</el-button><el-button data-test="mutation" link :type="s.row.enabled ? 'danger' : 'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'启用'}}</el-button></template></el-table-column></el-table>
    <div class="pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" background layout="total, sizes, prev, pager, next" :page-sizes="[20,50,100]" :total="total" @change="load"/></div>
    <el-dialog v-model="dialog" :title="editing?'编辑算力产品':'新增算力产品'" width="min(560px, calc(100% - 28px))"><el-alert v-if="editing" title="SKU 创建后不可修改，确保历史订单与账务可追溯。" type="info" :closable="false" style="margin-bottom:12px"/><el-form :model="form" label-width="90"><el-form-item label="SKU" required><el-input v-model="form.sku" :disabled="!!editing"/></el-form-item><el-form-item label="产品名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="GPU 型号" required><el-input v-model="form.gpuModel"/></el-form-item><el-form-item label="GPU 数量" required><el-input-number v-model="form.gpuCount" :min="1"/></el-form-item><el-form-item label="CPU 核数" required><el-input-number v-model="form.cpuCores" :min="1"/></el-form-item><el-form-item label="内存 GB" required><el-input-number v-model="form.memoryGb" :min="1"/></el-form-item><el-form-item label="价格（分）" required><el-input-number v-model="form.priceCent" :min="1" :precision="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="submitting" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<style scoped>.toolbar{align-items:center}.filters{display:flex;gap:8px;flex-wrap:wrap}.filters .el-input{width:280px}.filters .el-select{width:120px}.pager{display:flex;justify-content:flex-end;margin-top:16px}</style>
