<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api'
import { statusMeta } from '../utils/status'
type Cluster={id:number;code:string;name:string;region:string;status:string;nodeCount:number;gpuTotal:number;gpuAllocated:number}
type Node={id:number;name:string;gpuModel:string;gpuTotal:number;gpuAllocated:number;cpuCores:number;memoryGb:number;status:string}
const route=useRoute(),router=useRouter()
const routeClusterId=()=>{const parsed=Number(route.query.clusterId);return Number.isInteger(parsed)&&parsed>0?parsed:undefined}
const clusters=ref<Cluster[]>([]),nodes=ref<Node[]>([]),selected=ref<Cluster|null>(null),loading=ref(false),nodeLoading=ref(false),error=ref(''),keyword=ref(typeof route.query.keyword==='string'?route.query.keyword:''),status=ref(typeof route.query.status==='string'?route.query.status:'')
let ownRouteUpdate=false
const filtered=computed(()=>clusters.value.filter(cluster=>(!keyword.value||`${cluster.name} ${cluster.code} ${cluster.region}`.toLowerCase().includes(keyword.value.toLowerCase()))&&(!status.value||cluster.status===status.value)))
const utilization=(row:any)=>row.gpuTotal?Math.round(row.gpuAllocated/row.gpuTotal*100):0
const writeUrl=async()=>{ownRouteUpdate=true;try{await router.replace({query:{...(keyword.value?{keyword:keyword.value}:{}),...(status.value?{status:status.value}:{}),...(selected.value?{clusterId:String(selected.value.id)}:{})}})}finally{ownRouteUpdate=false}}
const load=async()=>{loading.value=true;error.value='';try{clusters.value=await api.get<Cluster[]>('/clusters');const target=clusters.value.find(item=>item.id===routeClusterId())||clusters.value.find(item=>item.id===selected.value?.id)||clusters.value[0];if(target)await pick(target,!routeClusterId())}catch(e:any){error.value=`${e.message||'加载资源失败'}${e.traceId?`（追踪 ID：${e.traceId}）`:''}`}finally{loading.value=false}}
const pick=async(row:Cluster|null|undefined,syncUrl=true)=>{if(!row)return;selected.value=row;if(syncUrl)await writeUrl();nodeLoading.value=true;try{nodes.value=await api.get<Node[]>(`/clusters/${row.id}/nodes`)}catch(e:any){error.value=`${e.message||'加载节点失败'}${e.traceId?`（追踪 ID：${e.traceId}）`:''}`;nodes.value=[]}finally{nodeLoading.value=false}}
const selectCluster=(row:Cluster|null)=>pick(row,true)
const updateFilters=()=>writeUrl()
watch(()=>route.query,async()=>{if(ownRouteUpdate)return;keyword.value=typeof route.query.keyword==='string'?route.query.keyword:'';status.value=typeof route.query.status==='string'?route.query.status:'';const target=clusters.value.find(item=>item.id===routeClusterId());if(target&&target.id!==selected.value?.id)await pick(target,false)})
onMounted(load)
</script>
<template><div class="resources"><div class="page-head"><div><h3>资源中心</h3><p class="muted">只读查看集群健康度、容量与分配利用率</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"><template #default><el-button link @click="load">重试</el-button></template></el-alert><div class="grid" style="grid-template-columns:1fr 1.5fr"><div class="panel"><div class="panel-title"><h3>计算集群</h3><span class="muted">{{filtered.length}} / {{clusters.length}} 个</span></div><div class="filters"><el-input v-model="keyword" clearable placeholder="集群名称 / 区域" @change="updateFilters" @keyup.enter="updateFilters"/><el-select v-model="status" clearable placeholder="健康状态" @change="updateFilters"><el-option label="健康" value="HEALTHY"/><el-option label="异常" value="UNHEALTHY"/></el-select></div><el-table v-loading="loading" :data="filtered" highlight-current-row empty-text="暂无符合条件的集群" @current-change="selectCluster"><el-table-column prop="name" label="集群"><template #default="s"><b>{{s.row.name}}</b><div class="muted">{{s.row.code}} · {{s.row.region}}</div></template></el-table-column><el-table-column label="容量" width="115"><template #default="s">{{s.row.gpuAllocated}} / {{s.row.gpuTotal}} GPU</template></el-table-column><el-table-column label="利用率" width="90"><template #default="s"><el-progress :percentage="utilization(s.row)" :stroke-width="8"/></template></el-table-column><el-table-column label="健康" width="85"><template #default="s"><el-tag :type="statusMeta(s.row.status).type">{{statusMeta(s.row.status).label}}</el-tag></template></el-table-column></el-table></div><div class="panel"><div class="panel-title"><div><h3>{{selected?.name||'节点列表'}}</h3><span class="muted">{{selected?`${selected.nodeCount} 个节点 · GPU 分配与容量详情`:'请选择集群'}}</span></div><el-button :disabled="!selected" :loading="nodeLoading" @click="pick(selected||undefined)">刷新节点</el-button></div><el-empty v-if="!nodeLoading&&!nodes.length" description="当前集群暂无节点"/><el-table v-else v-loading="nodeLoading" :data="nodes"><el-table-column prop="name" label="节点"/><el-table-column prop="gpuModel" label="GPU 型号"/><el-table-column label="GPU 分配"><template #default="s">{{s.row.gpuAllocated}} / {{s.row.gpuTotal}} <el-progress :percentage="utilization(s.row)" :stroke-width="7"/></template></el-table-column><el-table-column label="CPU / 内存"><template #default="s">{{s.row.cpuCores}} C / {{s.row.memoryGb}} GB</template></el-table-column><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.status==='READY'?'success':'warning'">{{s.row.status==='READY'?'就绪':s.row.status}}</el-tag></template></el-table-column></el-table></div></div></div></template>
<style scoped>.page-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.page-head h3{margin:0 0 5px}.page-head p{margin:0}.filters{display:flex;gap:8px;margin-bottom:12px}.filters .el-select{width:120px}</style>
